Repository COMP4350/Servus, pull requests merged in 2021-03, with the labels that each got.

#94 Filter appointments by date range
  server/src/db/models/appointment.js
  server/src/routes/appointment.js
  web/src/components/AppointmentCard.js
  web/src/components/map/ServiceWindow.js
  web/src/pages/Appointments.js
Labels: backend

#93 Setup API basename and fix mongo errors
  server/package-lock.json
  server/package.json
  server/src/app.js
  web/src/components/AppointmentCard.js
  web/src/components/ServiceList.js
  web/src/components/map/Map.js
  web/src/components/map/ServiceWindow.js
  web/src/index.js
  web/src/pages/Account.js
  web/src/pages/Appointments.js
  web/src/pages/Login.js
  web/src/pages/SignUp.js
Labels: enhancement

#97 Backend Unit Tests
  .github/workflows/CI.yml
  package-lock.json
  server/__tests__/App.test.js
  server/jest.config.json
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/db/index.js
  server/src/db/models/appointment.js
  server/src/db/models/service.js
  server/src/db/models/user.js
  server/src/index.js
  server/src/routes/appointment.js
  server/src/routes/index.js
  server/src/routes/services.js
  server/src/routes/user.js
  server/src/utils/authUtils.js
  server/test/appointment.test.js
  server/test/authUtils.test.js
  server/test/service.test.js
  server/test/test_utils.js
  server/test/user.test.js
Labels: backend, testing

#104 Availability
  .github/workflows/CI.yml
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/db/models/service.js
  server/src/routes/appointment.js
  server/src/routes/images.js
  server/src/utils/apptUtils.js
  server/test/appointment.test.js
  server/test/images.test.js
  server/test/service.test.js
  server/test/test-file.png
  server/test/test_utils.js
Labels: backend

#116 Additional component testing
  web/src/__tests__/components/UserInfo.test.js
  web/src/__tests__/components/__snapshots__/UserInfo.test.js.snap
Labels: testing

#121 At/tags selection
  server/package.json
  server/src/db/models/service.js
  server/src/routes/services.js
  server/test/test_utils.js
  web/src/components/AddService.js
Labels: backend, database, frontend
