Repository COMP4350/Servus, pull requests merged in 2021-04, with the labels that each got.

#122 Sidebar UI update
  server/src/routes/services.js
  web/src/App.js
  web/src/__tests__/components/ServiceList.test.js
  web/src/__tests__/components/__snapshots__/ServiceCard.test.js.snap
  web/src/__tests__/components/__snapshots__/ServiceList.test.js.snap
  web/src/components/AddService.js
  web/src/components/FilterList.js
  web/src/components/Header.js
  web/src/components/ServiceCard.js
  web/src/components/ServiceList.js
  web/src/components/map/Map.js
  web/src/pages/Home.js
Labels: enhancement, frontend

#125 Appointment calendar
  web/package-lock.json
  web/package.json
  web/src/__tests__/components/AppointmentCard.test.js
  web/src/__tests__/components/__snapshots__/AppointmentCard.test.js.snap
  web/src/components/AppointmentCard.js
  web/src/components/Calendar.js
  web/src/pages/Appointments.js
Labels: 4 days, enhancement, frontend, high priority

#130 Style Header
  web/src/__tests__/App.test.js
  web/src/components/Header.js
  web/src/images/servus_text.svg
Labels: 0.5 day, frontend, medium priority, refactor

#138 Profile REDO
  package-lock.json
  server/src/db/models/service.js
  server/src/db/models/user.js
  server/src/routes/services.js
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/__tests__/components/UserInfo.test.js
  web/src/__tests__/components/__snapshots__/UserInfo.test.js.snap
  web/src/components/AddService.js
  web/src/components/ImageBoard.js
  web/src/components/ServiceCard.js
  web/src/components/ServiceIconMap.js
  web/src/components/UserInfo.js
  web/src/components/map/Map.js
  web/src/components/map/MiniMap.js
  web/src/pages/Account.js
  web/src/pages/SignUp.js
  web/src/stylesheets/index.css
Labels: frontend, refactor

#139 Change duration to select
  web/src/components/AddService.js
Labels: frontend

#140 Adjust tag selection
  web/src/components/FilterList.js
  web/src/components/ServiceList.js
Labels: frontend

#141 Fix duration
  web/src/components/map/BookWindow.js
  web/src/components/map/ServiceWindow.js
Labels: 0.5 day

#143 Quick Profile Bug Fixes
  web/src/components/AddService.js
  web/src/components/ImageBoard.js
Labels: bug, frontend

#145 Show buyer and provider
  web/src/components/Calendar.js
Labels: 0.5 day

#157 At/style and comments
  server/src/routes/test.js
  server/src/utils/apptUtils.js
  server/test/test_utils.js
  web/cypress/integration/AdvertisePastWork.spec.js
  web/cypress/integration/BookAppointments.spec.js
  web/cypress/integration/FindServices.spec.js
  web/cypress/integration/ProvideServices.spec.js
  web/src/__tests__/components/__snapshots__/AddService.test.js.snap
  web/src/__tests__/components/__snapshots__/Header.test.js.snap
  web/src/__tests__/pages/__snapshots__/SignUp.test.js.snap
  web/src/components/AddService.js
  web/src/components/Calendar.js
  web/src/components/FilterList.js
  web/src/components/Header.js
  web/src/components/ServiceList.js
  web/src/components/UserInfo.js
  web/src/components/map/BookWindow.js
  web/src/components/map/Map.js
  web/src/pages/Home.js
  web/src/pages/SignUp.js
Labels: documentation, refactor
