Repository COMP4350/Servus, pull requests merged in 2021-02, with the labels that each got.

#40 Creates an api for accessing services
  .prettierignore
  .prettierrc.json
  README.md
  mobile/app.json
  package.json
  server/app.js
  server/bin/www
  server/db/stub.json
  server/package.json
  server/routes/index.js
  server/routes/services.js
  web/package.json
  web/public/index.html
  web/public/manifest.json
  web/src/App.css
  web/src/App.js
  web/src/App.test.js
  web/src/index.css
  web/src/index.js
  web/src/reportWebVitals.js
  wiki/meeting_log.md
Labels: backend, database, task

#43 Adds automatic Prettier formatting
  .github/workflows/format.yml
  package.json
Labels: testing

#42 Rz/landing page
  package.json
  web/package.json
  web/public/index.html
  web/src/App.js
  web/src/Components/About.js
  web/src/Components/Appointments.js
  web/src/Components/Contact.js
  web/src/Components/Header.js
  web/src/Components/Home.js
  web/src/images/landingPage.png
  web/src/index.js
Labels: frontend

#46 Setup Mongoose
  package.json
  server/app.js
  server/bin/www
  server/bin/www.js
  server/db/index.js
  server/db/models/service.js
  server/db/models/user.js
  server/package.json
  server/routes/index.js
  server/routes/services.js
Labels: backend, database

#48 Fixes github actions trigger issue
  .github/workflows/format.yml
  package-lock.json
  package.json
Labels: bug, testing

#50 Setup CI with GHA
  .github/workflows/CI.yml
  .github/workflows/format.yml
  mobile/.gitattributes
  mobile/.gitignore
  mobile/App.js
  mobile/package-lock.json
  mobile/package.json
  server/jest.config.json
  server/package-lock.json
  server/package.json
  server/src/__tests__/App.test.js
  server/src/app.js
  server/src/db/index.js
  server/src/db/models/service.js
  server/src/db/models/user.js
  server/src/db/stub.json
  server/src/index.js
  server/src/routes/index.js
  server/src/routes/services.js
  web/.gitignore
  web/__tests__/App.test.js
  web/package-lock.json
  web/src/App.css
  web/src/App.js
  web/src/__tests__/App.test.js
  web/src/components/About.js
  web/src/components/Appointments.js
  web/src/components/Contact.js
  web/src/components/Header.js
  web/src/components/Home.js
  web/src/logo.svg
  web/src/reportWebVitals.js
  web/src/stylesheets/index.css
Labels: testing

#59 Use hosted db service
  server/package-lock.json
  server/package.json
  server/src/app.js
Labels: database

#60 Create architecture diagram (redo)
  README.md
  wiki/diagrams.md
  wiki/layered_architecture.png
Labels: documentation

#73 Display user appointments
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/routes/appointment.js
  server/src/routes/services.js
  web/package-lock.json
  web/package.json
  web/src/components/AppointmentCard.js
  web/src/components/map/mapStyle.json
  web/src/pages/Appointments.js
Labels: frontend

#72 Adds fetched list of services and displays google map
  server/package-lock.json
  server/src/app.js
  web/package-lock.json
  web/package.json
  web/src/components/ServiceCard.js
  web/src/components/ServiceList.js
  web/src/components/map/Map.js
  web/src/pages/Home.js
Labels: 2 days

#74 Add ESLint
  .eslintrc.json
  .github/workflows/CI.yml
  mobile/.eslintrc.js
  mobile/.prettierrc.js
  mobile/App.js
  mobile/__tests__/App-test.js
  mobile/app.json
  mobile/babel.config.js
  mobile/index.js
  mobile/metro.config.js
  mobile/package-lock.json
  mobile/package.json
  package-lock.json
  package.json
  server/src/db/index.js
  server/src/db/models/user.js
  server/src/routes/appointment.js
  server/src/routes/auth.js
  server/src/routes/services.js
  server/src/routes/user.js
  web/__tests__/App.test.js
  web/package.json
  web/src/__tests__/App.test.js
  web/src/components/Header.js
Labels: testing

#76 WIP: Update the architecture diagram.
  wiki/diagrams.md
  wiki/layered_architecture.png
  wiki/mern_architecture.png
Labels: documentation

#78 WIP: Create UML class diagram.
  wiki/class_diagram_routes.png
  wiki/diagrams.md
Labels: documentation

#79 Add location to services
  .eslintrc.json
  server/src/db/models/service.js
  server/src/routes/services.js
  web/src/components/ServiceList.js
  web/src/components/map/Map.js
  web/src/images/flag_icon.png
  web/src/pages/Appointments.js
Labels: backend, frontend

#77 WIP: Sequence diagrams
  .prettierrc.json
  wiki/diagrams.md
  wiki/us_sequence_diagram_1.png
  wiki/us_sequence_diagram_2.png
Labels: documentation

#57 Meeting log - Sprint 2
  wiki/meeting_log.md
Labels: 3 points, documentation

#82 Add booking UI
  web/package-lock.json
  web/package.json
  web/src/components/map/Map.js
  web/src/components/map/ServiceWindow.js
Labels: frontend

#83 Create the testing plan and link to it in the readme.
  README.md
  wiki/SERVUS_Test_Plan_Sprint_2.pdf
Labels: documentation

#90 BugFix: book services
  server/package-lock.json
  server/src/routes/appointment.js
  server/src/utils/authUtils.js
  web/package-lock.json
  web/src/components/map/Map.js
  web/src/components/map/ServiceWindow.js
  web/src/pages/Account.js
  web/src/pages/Login.js
  web/src/pages/SignUp.js
Labels: bug
